$('.owl-carousel').owlCarousel({
   loop:true,
   margin:20,
   autoplay:true,
   autoplayTimeout:1000,
   autoplayHoverPause:true,
   nav:true,
   responsive:{
       0:{
           items:1
       },
       600:{
           items:3
       },
       1000:{
           items:4
       }
   }
})

$('.owl-carousel').owlCarousel({
    loop:true,
    margin:20,
    autoplay:true,
    autoplayTimeout:1000,
    autoplayHoverPause:true,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
 })
 
 